image: node:12.15.0-alpine3.11

before_script:
  - yarn install

cache:
  paths:
    - build/
    - node_modules/

# Compile the website into static assets.
build:
  stage: build
  script:
    - yarn run build

build-electron:
  image: electronuserland/builder:wine
  stage: build
  script:
    - yarn run build
    - yarn run dist

test:
  stage: test
  script:
    - yarn run test

.test:
  stage: test
  script:
    - yarn run test
